-- Add more mock jobs with IT categories
INSERT INTO jobs (id, title, company, location, type, category, description, salary_min, salary_max, salary_type, payment_frequency, payment_method, benefits, skills, positions, work_hours, is_remote, deadline, application_methods, contact_person, contact_phone, created_at, employer_id, status, urgent, latitude, longitude)
VALUES
  -- IT Jobs
  (gen_random_uuid(), 'Frontend Developer', 'TechSolutions Ltd', 'Nairobi, Kenya', 'Full-time', 'IT', 'We are looking for a skilled Frontend Developer to join our team. The ideal candidate should have experience with React, TypeScript, and modern CSS frameworks.', 80000, 120000, 'Range', 'Monthly', 'Bank Transfer', ARRAY['Transport allowance', 'Meals', 'Insurance'], ARRAY['React', 'TypeScript', 'CSS', 'JavaScript'], 2, '9 AM - 5 PM, Monday to Friday', true, '2024-12-31', ARRAY['Apply Directly via JobSoko', 'Submit CV & Cover Letter'], 'John Doe', '+254712345678', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -1.2921, 36.8219),
  
  (gen_random_uuid(), 'Backend Developer', 'DataTech Systems', 'Mombasa, Kenya', 'Full-time', 'IT', 'Looking for a Backend Developer with experience in Node.js, Express, and MongoDB. Must be able to design and implement scalable APIs.', 90000, 130000, 'Range', 'Monthly', 'Bank Transfer', ARRAY['Transport allowance', 'Insurance', 'Bonuses'], ARRAY['Node.js', 'Express', 'MongoDB', 'API Design'], 1, '8 AM - 4 PM, Monday to Friday', false, '2024-12-15', ARRAY['Apply Directly via JobSoko', 'Submit CV & Cover Letter'], 'Jane Smith', '+254723456789', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -4.0435, 39.6682),
  
  (gen_random_uuid(), 'Mobile App Developer', 'AppWorks Kenya', 'Kisumu, Kenya', 'Contract', 'IT', 'Seeking a Mobile App Developer with experience in React Native or Flutter. The project involves building a fintech application for the Kenyan market.', 70000, 100000, 'Range', 'Monthly', 'Mobile Money (M-Pesa, Airtel Money, etc.)', ARRAY['Flexible hours', 'Remote work options'], ARRAY['React Native', 'Flutter', 'Mobile Development', 'API Integration'], 2, 'Flexible hours', true, '2024-11-30', ARRAY['Apply Directly via JobSoko', 'Submit CV & Cover Letter'], 'Michael Ochieng', '+254734567890', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', true, -0.1022, 34.7617),
  
  (gen_random_uuid(), 'Data Scientist', 'Analytics Africa', 'Nairobi, Kenya', 'Full-time', 'Data Science', 'We are looking for a Data Scientist to analyze large datasets and build predictive models. Experience with Python, R, and machine learning required.', 100000, 150000, 'Range', 'Monthly', 'Bank Transfer', ARRAY['Transport allowance', 'Meals', 'Insurance', 'Bonuses'], ARRAY['Python', 'R', 'Machine Learning', 'Data Analysis'], 1, '9 AM - 5 PM, Monday to Friday', false, '2024-12-20', ARRAY['Apply Directly via JobSoko', 'Submit CV & Cover Letter'], 'Sarah Kamau', '+254745678901', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -1.2864, 36.8172),
  
  (gen_random_uuid(), 'Network Administrator', 'ConnectTech Solutions', 'Nakuru, Kenya', 'Full-time', 'Network Administration', 'Seeking a Network Administrator to manage and maintain our IT infrastructure. CCNA certification preferred.', 60000, 90000, 'Range', 'Monthly', 'Bank Transfer', ARRAY['Transport allowance', 'Insurance'], ARRAY['Network Administration', 'CCNA', 'Cisco', 'Troubleshooting'], 1, '8 AM - 5 PM, Monday to Friday', false, '2024-11-15', ARRAY['Apply Directly via JobSoko', 'Submit CV & Cover Letter'], 'David Mwangi', '+254756789012', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -0.3031, 36.0800),
  
  (gen_random_uuid(), 'Cybersecurity Analyst', 'SecureNet Kenya', 'Nairobi, Kenya', 'Full-time', 'Cybersecurity', 'Looking for a Cybersecurity Analyst to help protect our systems from threats. Experience with penetration testing and security audits required.', 90000, 130000, 'Range', 'Monthly', 'Bank Transfer', ARRAY['Transport allowance', 'Meals', 'Insurance', 'Bonuses'], ARRAY['Cybersecurity', 'Penetration Testing', 'Security Audits', 'Threat Analysis'], 1, '9 AM - 5 PM, Monday to Friday', false, '2024-12-10', ARRAY['Apply Directly via JobSoko', 'Submit CV & Cover Letter'], 'Lucy Njeri', '+254767890123', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', true, -1.2933, 36.8172),
  
  -- Construction Jobs
  (gen_random_uuid(), 'Construction Worker', 'BuildRight Construction', 'Nairobi, Kenya', 'Full-time', 'Construction', 'We are hiring construction workers for our new residential project. Experience in building and construction required.', 30000, 45000, 'Range', 'Monthly', 'Mobile Money (M-Pesa, Airtel Money, etc.)', ARRAY['Transport allowance', 'Meals', 'Uniform'], ARRAY['Construction', 'Building', 'Physical Labor'], 10, '7 AM - 5 PM, Monday to Saturday', false, '2024-11-20', ARRAY['Apply Directly via JobSoko', 'Walk-in Interview'], 'James Kamau', '+254778901234', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -1.2980, 36.8048),
  
  (gen_random_uuid(), 'Plumber', 'WaterWorks Kenya', 'Mombasa, Kenya', 'Part-time', 'Construction', 'Looking for experienced plumbers for residential and commercial projects. Must have own tools.', 2000, 3000, 'Fixed Salary', 'Daily', 'Cash', ARRAY['Transport allowance'], ARRAY['Plumbing', 'Pipe Fitting', 'Maintenance'], 5, '8 AM - 5 PM, Flexible days', false, '2024-11-25', ARRAY['Apply Directly via JobSoko', 'Call or WhatsApp Employer'], 'Peter Omondi', '+254789012345', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -4.0435, 39.6682),
  
  -- Retail Jobs
  (gen_random_uuid(), 'Retail Sales Associate', 'ShopMart Kenya', 'Nairobi, Kenya', 'Full-time', 'Retail', 'We are looking for friendly and energetic Sales Associates to join our team. Previous retail experience preferred.', 25000, 35000, 'Range', 'Monthly', 'Bank Transfer', ARRAY['Transport allowance', 'Meals', 'Uniform'], ARRAY['Customer Service', 'Sales', 'Communication', 'Retail'], 5, '9 AM - 6 PM, Shifts', false, '2024-11-30', ARRAY['Apply Directly via JobSoko', 'Walk-in Interview'], 'Mary Wanjiku', '+254790123456', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -1.2864, 36.8250),
  
  (gen_random_uuid(), 'Cashier', 'QuickMart Supermarket', 'Kisumu, Kenya', 'Part-time', 'Retail', 'Hiring cashiers for our busy supermarket. Must be good with numbers and have excellent customer service skills.', 20000, 25000, 'Range', 'Monthly', 'Bank Transfer', ARRAY['Meals', 'Uniform'], ARRAY['Customer Service', 'Cash Handling', 'Communication'], 3, '8 AM - 8 PM, Shifts', false, '2024-11-15', ARRAY['Apply Directly via JobSoko', 'Walk-in Interview'], 'John Otieno', '+254701234567', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -0.1022, 34.7617),
  
  -- Hospitality Jobs
  (gen_random_uuid(), 'Hotel Receptionist', 'Serena Hotel', 'Nairobi, Kenya', 'Full-time', 'Hospitality', 'We are looking for a professional Hotel Receptionist to welcome guests and handle check-ins/check-outs.', 35000, 45000, 'Range', 'Monthly', 'Bank Transfer', ARRAY['Transport allowance', 'Meals', 'Uniform', 'Insurance'], ARRAY['Customer Service', 'Communication', 'Computer Skills'], 2, '8 AM - 8 PM, Shifts', false, '2024-12-05', ARRAY['Apply Directly via JobSoko', 'Submit CV & Cover Letter'], 'Sarah Njoroge', '+254712345678', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -1.2721, 36.8219),
  
  (gen_random_uuid(), 'Chef', 'Taste of Kenya Restaurant', 'Mombasa, Kenya', 'Full-time', 'Hospitality', 'Hiring experienced chefs specializing in Kenyan and international cuisine. Must have at least 2 years of experience.', 40000, 60000, 'Range', 'Monthly', 'Bank Transfer', ARRAY['Transport allowance', 'Meals', 'Uniform', 'Insurance'], ARRAY['Cooking', 'Food Preparation', 'Menu Planning'], 2, '10 AM - 10 PM, Shifts', false, '2024-11-20', ARRAY['Apply Directly via JobSoko', 'Submit CV & Cover Letter'], 'Daniel Mwangi', '+254723456789', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -4.0435, 39.6682),
  
  -- Delivery Jobs
  (gen_random_uuid(), 'Delivery Driver', 'FastDelivery Kenya', 'Nairobi, Kenya', 'Freelance/Gig', 'Delivery', 'Looking for motorcycle delivery drivers. Must have own motorcycle and valid driving license.', 1500, NULL, 'Fixed Salary', 'Daily', 'Mobile Money (M-Pesa, Airtel Money, etc.)', ARRAY['Flexible hours'], ARRAY['Driving', 'Navigation', 'Time Management'], 10, 'Flexible hours', false, '2024-12-15', ARRAY['Apply Directly via JobSoko', 'Call or WhatsApp Employer'], 'Joseph Kimani', '+254734567890', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', true, -1.2864, 36.8172),
  
  (gen_random_uuid(), 'Warehouse Assistant', 'LogisticsPro Kenya', 'Nakuru, Kenya', 'Full-time', 'Delivery', 'Hiring warehouse assistants to help with inventory management and order fulfillment.', 25000, 35000, 'Range', 'Monthly', 'Bank Transfer', ARRAY['Transport allowance', 'Meals', 'Uniform'], ARRAY['Inventory Management', 'Physical Labor', 'Organization'], 5, '8 AM - 5 PM, Monday to Friday', false, '2024-11-25', ARRAY['Apply Directly via JobSoko', 'Walk-in Interview'], 'Grace Wambui', '+254745678901', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -0.3031, 36.0800),
  
  -- Cleaning Jobs
  (gen_random_uuid(), 'Office Cleaner', 'CleanPro Services', 'Nairobi, Kenya', 'Part-time', 'Cleaning', 'Hiring office cleaners for corporate buildings in Nairobi CBD. Morning and evening shifts available.', 15000, 20000, 'Range', 'Monthly', 'Mobile Money (M-Pesa, Airtel Money, etc.)', ARRAY['Transport allowance', 'Uniform'], ARRAY['Cleaning', 'Janitorial Services'], 8, '6 AM - 9 AM or 5 PM - 8 PM', false, '2024-11-15', ARRAY['Apply Directly via JobSoko', 'Walk-in Interview'], 'Agnes Muthoni', '+254756789012', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -1.2864, 36.8219),
  
  (gen_random_uuid(), 'Domestic Worker', 'HomeCare Agency', 'Kisumu, Kenya', 'Full-time', 'Cleaning', 'Looking for domestic workers for residential homes. Duties include cleaning, laundry, and basic cooking.', 20000, 30000, 'Range', 'Monthly', 'Cash', ARRAY['Housing', 'Meals'], ARRAY['Cleaning', 'Cooking', 'Laundry'], 5, '7 AM - 5 PM, Monday to Saturday', false, '2024-11-20', ARRAY['Apply Directly via JobSoko', 'Call or WhatsApp Employer'], 'Jane Akinyi', '+254767890123', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -0.1022, 34.7617),
  
  -- Security Jobs
  (gen_random_uuid(), 'Security Guard', 'SecureKenya Ltd', 'Nairobi, Kenya', 'Full-time', 'Security', 'Hiring security guards for residential and commercial properties. Previous experience preferred.', 25000, 35000, 'Range', 'Monthly', 'Bank Transfer', ARRAY['Transport allowance', 'Uniform', 'Insurance'], ARRAY['Security', 'Surveillance', 'Communication'], 10, '12-hour shifts, day and night', false, '2024-12-10', ARRAY['Apply Directly via JobSoko', 'Walk-in Interview'], 'Samuel Maina', '+254778901234', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -1.2864, 36.8172),
  
  (gen_random_uuid(), 'Night Watchman', 'Guardian Security', 'Mombasa, Kenya', 'Full-time', 'Security', 'Looking for night watchmen for residential compounds. Must be alert and responsible.', 20000, 25000, 'Range', 'Monthly', 'Mobile Money (M-Pesa, Airtel Money, etc.)', ARRAY['Uniform'], ARRAY['Security', 'Vigilance'], 5, '6 PM - 6 AM, Night shifts', false, '2024-11-30', ARRAY['Apply Directly via JobSoko', 'Call or WhatsApp Employer'], 'Omar Hassan', '+254789012345', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -4.0435, 39.6682),
  
  -- Farming Jobs
  (gen_random_uuid(), 'Farm Worker', 'GreenFields Farm', 'Nakuru, Kenya', 'Seasonal', 'Farming', 'Hiring farm workers for the harvest season. Experience in crop harvesting preferred.', 1200, NULL, 'Fixed Salary', 'Daily', 'Cash', ARRAY['Meals', 'Transport allowance'], ARRAY['Farming', 'Harvesting', 'Physical Labor'], 20, '6 AM - 4 PM, Monday to Saturday', false, '2024-11-15', ARRAY['Apply Directly via JobSoko', 'Walk-in Interview'], 'David Kiprop', '+254790123456', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -0.3031, 36.0800),
  
  (gen_random_uuid(), 'Greenhouse Attendant', 'HydroGrow Kenya', 'Naivasha, Kenya', 'Full-time', 'Farming', 'Looking for greenhouse attendants to help with plant care and maintenance.', 25000, 30000, 'Range', 'Monthly', 'Bank Transfer', ARRAY['Transport allowance', 'Meals', 'Housing'], ARRAY['Farming', 'Plant Care', 'Irrigation'], 5, '7 AM - 4 PM, Monday to Saturday', false, '2024-11-25', ARRAY['Apply Directly via JobSoko', 'Submit CV & Cover Letter'], 'Rose Njeri', '+254701234567', NOW(), (SELECT id FROM users WHERE role = 'employer' LIMIT 1), 'active', false, -0.7136, 36.4355)
ON CONFLICT DO NOTHING;